name: Build my Nagios image and push to my registry

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

jobs:
  slack-start:
    uses: pgmac-net/pg-actions/.github/workflows/slack-notify-start.yml@main
    secrets: inherit

  build-n-push:
    needs: [slack-start]
    permissions:
      id-token: write
      attestations: write
      actions: read
      contents: write
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set the image version
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx (remote BuildKit)
        uses: docker/setup-buildx-action@v3
        with:
          driver: remote
          endpoint: tcp://buildkitd.arc-runners.svc.cluster.local:1234

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: macro.int.pgmac.net:5000/nagios:${{ inputs.tags || steps.vars.outputs.tag }}

      - name: Run Syft SBoM scan
        uses: anchore/sbom-action@v0.17.8
        with:
          image: macro.int.pgmac.net:5000/nagios:${{ inputs.tags || steps.vars.outputs.tag }}
          format: cyclonedx-json
          output-file: syft-sbom.json
          artifact-name: syft-sbom.json

      - name: Upload SBoM to GitHub Artifact storage
        uses: actions/upload-artifact@v4
        with:
          name: syft-sbom.json
          path: "syft-sbom.json"
          retention-days: 2
          overwrite: true

      - name: SHA256 hash the SBoM
        id: sha256
        run: echo "SHA256=$(sha256sum syft-sbom.json | cut -d ' ' -f1)" >> $GITHUB_ENV

      - name: Attest the SBoM
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: macro.int.pgmac.net:5000/Docker-Nagios/syft-sbom.json
          subject-digest: sha256:${{ env.SHA256 }}
          show-summary: true
          push-to-registry: false

      - name: Upload SBoM to Dependency Track
        uses: DependencyTrack/gh-upload-sbom@v3.1.0
        with:
          serverhostname: "dtrack.int.pgmac.net"
          protocol: "https"
          apikey: ${{ secrets.DT_APIKEY }}
          project: ${{ secrets.DT_PROJECT_UUID }}
          bomfilename: "syft-sbom.json"
          autocreate: false

  slack-end:
    if: always()
    needs: [slack-start, build-n-push]
    uses: pgmac-net/pg-actions/.github/workflows/slack-notify-end.yml@main
    with:
      ts: ${{ needs.slack-start.outputs.ts }}
      start: ${{ needs.slack-start.outputs.start }}
      startfmt: ${{ needs.slack-start.outputs.startfmt }}
      status: ${{ needs.build-n-push.result }}
    secrets: inherit
